openapi: 3.0.3
info:
  title: OpenAPI schema for template .
components:
  schemas:
    variables:
      type: object
      required:
      - esxi_host_ip
      - esxi_network
      - esxi_password
      - vcenter_host_gateway
      - vcenter_host_ip
      - vcenter_hostname
      - vcenter_os_password
      - vcenter_sso_password
      - vcenter_version
      properties:
        image_name:
          title: vcenter构建器镜像
          type: string
          description: Name for the vcenter_builder image
          default: vcenter-builder-by-terraform
          x-walrus-ui:
            group: Basic
            order: 2
        create_image:
          title: Create Image
          type: boolean
          description: Flag to determine whether to create the image. Set to true
            to create the image, false to use image name to search in backupstorage.
          default: true
          x-walrus-ui:
            group: Basic
            order: 3
        image_url:
          title: 构建器镜像 Url
          type: string
          description: URL to download the image from
          default: http://192.168.200.100/mirror/jiajian.chi/os/base/vcsa_builder_compressed.qcow2
          x-walrus-ui:
            group: Basic
            order: 3
        backup_storage_name:
          title: 镜像服务器
          type: string
          description: Name of the backup storage to use
          default: bs
          x-walrus-ui:
            group: Basic
            order: 4
        instance_name:
          title: 构建器实例名
          type: string
          description: Name for the vcenter_builder instance
          default: vcenter_builder
          x-walrus-ui:
            group: Basic
            order: 5
        l3_network_name:
          title: 三层网络
          type: string
          description: Name of the L3 network to use
          default: test
          x-walrus-ui:
            group: Basic
            order: 6
        instance_offering_name:
          title: 计算规格
          type: string
          description: Name of the instance offering to use
          default: min
          x-walrus-ui:
            group: Basic
            order: 7
        ssh_user:
          title: Ssh User
          type: string
          description: SSH username for remote access
          default: zstack
          readOnly: true
          x-walrus-ui:
            group: Basic
            order: 8
        ssh_password:
          title: Ssh Password
          type: string
          description: SSH password for remote access
          default: ZStack@123
          readOnly: true
          x-walrus-ui:
            group: Basic
            order: 9
        esxi_host_ip:
          title: Esxi主机IP
          type: string
          description: The IP address of the ESXi host
          x-walrus-ui:
            group: Basic
            order: 10
        esxi_username:
          title: Esxi用户名
          type: string
          description: The username for the ESXi host
          default: root
          readOnly: true
          x-walrus-ui:
            group: Basic
            order: 11
        esxi_password:
          title: Esxi密码
          type: string
          description: TEsxi密码，自动构建的无人值守密码，默认是ZStack@123
          default: ZStack@123
          format: password
          writeOnly: true
          x-walrus-ui:
            group: Basic
            order: 12
        esxi_network:
          title: Esxi网络
          type: string
          description: The deployment network name in ESXi
          default: VM Network
          x-walrus-ui:
            group: Basic
            order: 13
        vcenter_hostname:
          title: Vcenter主机名
          type: string
          description: The name of the vCenter VM to deploy
          x-walrus-ui:
            group: Basic
            order: 14
        vcenter_host_ip:
          title: Vcenter Ip
          type: string
          description: vcenter_host_ip 的IP地址默认是ESXI网络的桥接，也是ZStack的扁平或公有网络，请注意不要冲突，不要填写任何0.1的网关地址
          x-walrus-ui:
            group: Basic
            order: 15
        vcenter_host_gateway:
          title: Vcenter网关
          type: string
          description: The gateway IP for the vCenter appliance
          x-walrus-ui:
            group: Basic
            order: 16
        vcenter_host_prefix:
          title: Vcenter Host Prefix
          type: string
          description: The CIDR prefix (e.g., 24) for the vCenter network
          default: "16"
          x-walrus-ui:
            group: Basic
            order: 17
        dns_servers:
          title: Dns Servers
          type: array
          description: List of DNS server IPs
          default:
          - 223.5.5.5
          items:
            type: string
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 18
        vcenter_os_password:
          title: Vcenter OS 密码
          type: string
          description: Password for the vCenter OS root user
          default: ZStack@123
          format: password
          writeOnly: true
          x-walrus-ui:
            group: Basic
            order: 19
        vcenter_sso_password:
          title: Vcenter SSO 密码
          type: string
          description: Password for the SSO administrator
          default: ZStack@123
          format: password
          writeOnly: true
          x-walrus-ui:
            group: Basic
            order: 20
        vcenter_version:
          title: Vcenter版本
          type: string
          description: 'The version of vCenter to deploy (allowed: 7.0, 8.0)'
          x-walrus-ui:
            group: Basic
            order: 21
        expunge:
          title: Expunge
          type: boolean
          default: true
          x-walrus-ui:
            group: Basic
            order: 23
      x-walrus-ui:
        groupOrder:
        - Basic
